### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory 'C:\tmp\ATOM-HR-710RHE11L1C680K9.source.js'

### ISSUE THREAD

**Issue by Trudko** [webBoxio/atom-hashrocket#5]
1. Creating simple js file :
var a = 1;
var b = 2;
var c = a + b;
2. Run has rocket insert command:
var a = 1;
var b = 2;
var c = a + b;

//=> 
3. Run the rocket run command

**Atom Version**: 0.184.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [hashrocket](https://github.com/webBoxio/atom-hashrocket) package, v0.4.3

### Stack Trace

Uncaught Error: ENOENT, no such file or directory 'C:\tmp\ATOM-HR-710RHE11L1C680K9.source.js'

```
At fs.js:503

Error: ENOENT, no such file or directory 'C:\tmp\ATOM-HR-710RHE11L1C680K9.source.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\atom\common\lib\asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1116:15)
  at Object.module.exports.run (C:\Users\Peter\.atom\packages\hashrocket\lib\hashrocket.coffee:108:8)
  at atom-workspace.<anonymous> (C:\Users\Peter\.atom\packages\hashrocket\lib\hashrocket.coffee:10:54)
  at atom-workspace.handler (c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\app\src\space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at atom-workspace.elemData.handle (c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\app\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\app\node_modules\command-palette\lib\command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (c:\Users\Peter\AppData\Local\atom\app-0.184.0\resources\app\src\window-event-handler.js:182:20)

```

### Commands

```
     -0:37.8 hashrocket:insert (atom-text-editor.editor)
     -0:17.2 editor:select-to-first-character-of-line (atom-text-editor.editor)
     -0:16.8 core:cut (atom-text-editor.editor)
     -0:16.6 core:delete (atom-text-editor.editor)
     -0:16.3 core:move-down (atom-text-editor.editor)
     -0:16.2 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -0:15.6 refactor:done (atom-text-editor.editor)
     -0:15.6 editor:newline (atom-text-editor.editor)
     -0:13.8 command-palette:toggle (atom-text-editor.editor)
     -0:12.2 core:move-down (atom-text-editor.editor.mini)
     -0:11.8 core:confirm (atom-text-editor.editor.mini)
     -0:11.8 hashrocket:insert (atom-text-editor.editor)
     -0:11.1 command-palette:toggle (atom-text-editor.editor)
  2x -0:09.8 core:backspace (atom-text-editor.editor.mini)
     -0:08.5 core:confirm (atom-text-editor.editor.mini)
     -0:08.5 hashrocket:run (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-phpcs",
      "turbo-javascript",
      "jslint",
      "preview-plus",
      "linter-jshint",
      "jshint",
      "command-toolbar"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v1.5.0
atom-minjs, v0.2.12
coffee-compile, v0.11.0
hashrocket, v0.4.3
js-refactor, v0.3.0
jsformat, v0.7.18
keybinding-cheatsheet, v0.0.8
linter, v0.12.0
linter-lsc, v1.1.2
linter-php, v0.0.11
linter-phpmd, v0.0.10
minifier, v0.2.0
notebook, v0.4.0
php-server, vundefined
phpunit, v1.0.9
phpunit-snippets, v0.1.0
refactor, v0.4.1
script, v2.18.0
script-runner, v1.7.1

# Dev
No dev packages
```

**Comment by ChanceM** [comment]
@Trudko I have a windows compatible version built. Still trying to confirm tests in Linux/Mac. Hang in there.
