### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prefix' of undefined

### ISSUE THREAD

**Issue by jjeroennl** [webBoxio/atom-hashrocket#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: elementary OS
**Thrown From**: [hashrocket](https://github.com/webBoxio/atom-hashrocket) package, v0.4.8

### Stack Trace

Uncaught TypeError: Cannot read property 'prefix' of undefined

```
At /home/jeroen/.atom/packages/hashrocket/lib/hashrocket.coffee:84

TypeError: Cannot read property 'prefix' of undefined
  at Object.module.exports.insertHashrocket (/home/jeroen/.atom/packages/hashrocket/lib/hashrocket.coffee:84:39)
  at atom-text-editor.<anonymous> (/home/jeroen/.atom/packages/hashrocket/lib/hashrocket.coffee:45:8)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -1:47 core:move-right (atom-text-editor.editor.is-focused)
  3x -1:31 core:undo (atom-text-editor.editor.is-focused)
     -1:28.7.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -1:23.3.0 core:undo (atom-text-editor.editor.is-focused)
 14x -1:21.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:19.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:15 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:14.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:13.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:12.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:12.8.0 editor:indent (atom-text-editor.editor.is-focused)
  8x -0:11.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.9.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:06.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:05.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "hashrocket": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-glsl, v0.2.3
autocomplete-modules, v1.0.0
autocomplete-php, v0.3.6
autocomplete-python, v0.5.1
color-picker, v2.0.7
file-icons, v1.5.8
file-templates, v0.1.1
hashrocket, v0.4.8
linter, v1.1.0
linter-javac, v0.1.4
linter-jshint, v0.1.7
linter-php, v0.0.15
minimap, v4.10.1
pigments, v0.8.1

# Dev
No dev packages
```

**Comment by mallikarjunayaddala** [comment]
Same error for me

**Comment by vs4vijay** [comment]
Any update on solution?
